AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 85
  IgnoreCopDirectives: true

Metrics/BlockLength:
  Exclude:
    - "gladius.gemspec"
  ExcludedMethods:
    - "configure"
    - "describe"